Repository sprint-part3-team11/taskify, pull requests merged in 2024-04, with the labels that each got.

#2 프로젝트 생성 및 초기 개발환경 셋팅
  .babelrc
  .eslintrc.json
  .gitignore
  .prettierrc
  next.config.mjs
  package-lock.json
  package.json
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/hj.tsx
  src/pages/index.tsx
  src/pages/js.tsx
  src/pages/jy.tsx
  src/pages/mj.tsx
  src/pages/sh.tsx
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: ✨ enhancement

#5 [공통] 셀렉트 박스 구현
  public/icon/arrowButton.svg
  public/icon/checkIcon.svg
  src/components/common/SelectBox.tsx
  src/constants/MEDIAQUERIES.tsx
  src/hooks/useClickOutside.tsx
  src/pages/jy.tsx
  tsconfig.json
Labels: 🖥️ui

#11 [공통] 이미지 파일 업로드 컴포넌트 구현
  public/icon/addImgIcon.svg
  public/icon/editPencilIcon.svg
  src/components/common/ImgFileUpload.tsx
  src/pages/jy.tsx
Labels: ✨ enhancement, 🖥️ui

#17 [공통] 색상 선택 컴포넌트 구현
  package.json
  public/icon/colorCheckIcon.svg
  src/components/common/ColorSelector.tsx
  src/pages/_app.tsx
  src/pages/jy.tsx
  yarn.lock
Labels: ✨ enhancement, 🖥️ui

#25 [공통] 대시보드 헤더 구현
  next.config.mjs
  src/components/common/DashBoardHeader/SideBar.tsx
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/tag/HashTag.tsx
  src/components/common/tag/StateTag.tsx
  src/pages/hj.tsx
Labels: ✨ enhancement, 🖥️ui

#26 [공통] 아바타 이미지 컴포넌트
  next.config.mjs
  src/components/common/AvatarImage.tsx
  src/pages/js.tsx
Labels: ✨ enhancement, 🖥️ui

#27 [공통] 컬럼 생성 모달 구현 & 로그인 관련 모달 구현
  .eslintrc.json
  src/components/common/Modal/PasswordWarnModal.tsx
  src/components/common/modal/AddNewColumnsModal.tsx
  src/components/common/modal/BackDropModal.tsx
  src/components/common/modal/WarningModal.tsx
  src/constants/WARNING_MODAL_MESSAGES.ts
  src/pages/mj.tsx
Labels: ✨ enhancement, 🖥️ui

#30 [공통] 사이드바 구현
  public/icon/addDashboardBox.svg
  public/icon/creatByMe.svg
  public/icon/logo.svg
  public/icon/logoText.svg
  src/components/common/CircleColor.tsx
  src/components/common/SideBar.tsx
  src/pages/jy.tsx
Labels: ✨ enhancement, 🖥️ui

#37 [공통] 팀원 초대 모달 구현
  src/components/common/modal/BackDropModal.tsx
  src/components/common/modal/ColumnsManageModal.tsx
  src/components/common/modal/NewColumnsModal.tsx
  src/components/common/modal/TeamMemberInviteModal.tsx
  src/components/common/modal/WarningModal.tsx
  src/constants/WARNING_MODAL_MESSAGES.ts
  src/pages/mj.tsx
  src/utils/validators.ts
Labels: ✨ enhancement, 🖥️ui

#32 [공통] 컬럼 수정(관리) 모달 구현
  .eslintrc.json
  src/components/common/modal/BackDropModal.tsx
  src/components/common/modal/ColumnsManageModal.tsx
Labels: ✨ enhancement, 🖥️ui

#39 [공통] 이미지 첨부 컴포넌트 이슈
  public/icon/addIcon.svg
  public/icon/editPencilIcon.svg
  src/components/common/ColorSelector.tsx
  src/components/common/ImgFileUpload.tsx
  src/pages/jy.tsx
Labels: 🔨fix, 🖥️ui

#34 [페이지] 랜딩 페이지 구현
  public/icon/email.svg
  public/icon/facebook.svg
  public/icon/insta.svg
  public/image/landinTodo.png
  public/image/landing.png
  public/image/landingCard.png
  public/image/landingDashboardSetting.png
  public/image/landingInvitationSetting.png
  public/image/landingMembersSetting.png
  src/components/landing/Footer.tsx
  src/components/landing/LandingHeader.tsx
  src/components/landing/LandingMiddle.tsx
  src/components/landing/LandingSetting.tsx
  src/constants/LANDING_SETTING_ITEMS.ts
  src/pages/index.tsx
Labels: 🖥️ui

#43 [공통] rem단위 전면 긴급 수정
  src/components/common/ColorSelector.tsx
  src/components/common/ImgFileUpload.tsx
  src/components/common/SelectBox.tsx
  src/pages/jy.tsx
Labels: 🔨fix

#42 [공통] 폼 컴포넌트 구현
  .eslintrc.json
  src/components/common/AvatarImage.tsx
  src/components/form/Form.tsx
  src/pages/js.tsx
Labels: ✨ enhancement, 🖥️ui

#46 [공통] 할일 생성 모달(미완성)
  .eslintrc.json
  package.json
  public/icon/calendarIcon.svg
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/DateSelector.tsx
  src/components/common/SelectBox.tsx
  src/components/common/SideBar.tsx
  src/components/dashboard/Layout.tsx
  src/components/dashboard/modal/ToDoCreateModal.tsx
  src/constants/MEDIAQUERIES.tsx
  src/pages/sh.tsx
  src/styles/buttonStyle.ts
  src/styles/commonStyle.ts
  src/styles/datePickerStyle.ts
  src/styles/theme.ts
  yarn.lock
Labels: 🐞bug, ✨ enhancement, 🖥️ui

#50 [공통] 할 일 카드 모달 구현
  public/icon/closeIcon.svg
  public/icon/kebabIcon.svg
  src/components/common/DashBoardHeader/SideBar.tsx
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/Modal/card-confirm/CardConfirmModal.tsx
  src/components/common/Modal/card-confirm/Comment.tsx
  src/components/common/Modal/card-confirm/CommentForm.tsx
  src/components/common/Modal/card-confirm/CommentItem.tsx
  src/components/common/Modal/card-confirm/CommentList.tsx
  src/components/common/Modal/card-confirm/ContentAndImageBox.tsx
  src/components/common/Modal/card-confirm/MainBox.tsx
  src/components/common/Modal/card-confirm/MockData.ts
  src/components/common/Modal/card-confirm/ModalHeader.tsx
  src/components/common/Modal/card-confirm/SideBox.tsx
  src/components/common/Modal/card-confirm/TagBox.tsx
  src/components/common/Modal/card-confirm/types.ts
  src/hooks/useWindowSize.tsx
  src/pages/hj.tsx
  src/utils/date.tsx
Labels: ✨ enhancement, 🖥️ui

#56 [공통] 사이드바 너비 조정
  src/components/common/SelectBox.tsx
  src/components/common/SideBar.tsx
Labels: 🔨fix, 🖥️ui

#54 [공통] 셀렉트 박스 input으로 변경
  src/components/common/SelectBox.tsx
Labels: 🖥️ui

#57 [공통] 페이지 레이아웃 구현 (사이드바 & 대시보드 헤더)
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/PageLayout.tsx
  src/components/common/SideBar.tsx
  src/pages/hj.tsx
Labels: ✨ enhancement, 🖥️ui

#62 [공통] 카드 컴포넌트 구현
  public/icon/smallCalendarIcon.svg
  src/components/common/Card.tsx
  src/components/common/ColorSelector.tsx
  src/components/common/modal/BackDropModal.tsx
  src/components/common/modal/ColumnsManageModal.tsx
  src/components/common/modal/card-confirm/CardConfirmModal.tsx
  src/components/common/modal/card-confirm/Comment.tsx
  src/components/common/modal/card-confirm/CommentForm.tsx
  src/components/common/modal/card-confirm/CommentItem.tsx
  src/components/common/modal/card-confirm/CommentList.tsx
  src/components/common/modal/card-confirm/ContentAndImageBox.tsx
  src/components/common/modal/card-confirm/MainBox.tsx
  src/components/common/modal/card-confirm/MockData.ts
  src/components/common/modal/card-confirm/ModalHeader.tsx
  src/components/common/modal/card-confirm/SideBox.tsx
  src/components/common/modal/card-confirm/TagBox.tsx
  src/components/common/modal/card-confirm/types.ts
  src/components/common/tag/HashTag.tsx
  src/pages/mj.tsx
Labels: ✨ enhancement, 🖥️ui

#60 [페이지] 마이페이지 레이아웃 변경
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/PageLayout.tsx
  src/components/my-page/MypageHeader.tsx
  src/components/my-page/ProfileChange.tsx
  src/pages/mypage.tsx
Labels: 🤓refactor, 🖥️ui

#65 [API] 엔드포인트 상수 설정
  src/constants/API
Labels: ✨ enhancement, ⚙️api

#66 [공통] 폼 컴포넌트 구현
  src/components/common/input/FormInput.tsx
  src/components/common/input/InputField.tsx
  src/components/common/modal/ColumnsManageModal.tsx
  src/components/common/modal/NewColumnsModal.tsx
  src/components/common/modal/TeamMemberInviteModal.tsx
  src/components/form/Form.tsx
  src/constants/SCHEMA.ts
  src/constants/VALIDATION.ts
  src/pages/js.tsx
  src/utils/validators.ts
Labels: ✨ enhancement, 🖥️ui

#67 [페이지] 나의 대시보드 페이지 UI 구현
  public/icon/crownIcon.svg
  public/icon/messageIcon.svg
  public/icon/rightArraowIcon.svg
  public/icon/searchIcon.svg
  src/components/common/button/AddIconButton.tsx
  src/components/dashboard/my-board/DashBoardList.tsx
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/components/dashboard/my-board/NoInvitation.tsx
  src/components/dashboard/my-board/SearchBar.tsx
  src/constants/LIST_INFO.ts
  src/pages/my-dashboard.tsx
  src/styles/commonStyle.ts
  src/utils/handleEnterKeyDown.ts
Labels: ✨ enhancement, 🖥️ui

#73 [페이지] 로그인/회원가입 페이지 레이아웃 구현
  public/icon/logoImg.svg
  public/icon/taskify.svg
  src/components/form/FormLayout.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/js.tsx
Labels: ✨ enhancement, 🖥️ui

#70 [페이지] 마이페이지 input 컴포넌트 수정
  src/components/common/input/FormInput.tsx
  src/components/my-page/PasswordChange.tsx
  src/components/my-page/ProfileChange.tsx
Labels: 🤓refactor, 🖥️ui

#72 [페이지] 대시보드 수정 페이지 구현
  public/icon/arrowLeft.svg
  public/icon/arrowRight.svg
  public/icon/plus.svg
  public/icon/setting.svg
  src/components/common/DashBoardHeader/index.tsx
  src/components/common/PageLayout.tsx
  src/components/common/SideBar.tsx
  src/components/edit-page/InviteHistoryListBox.tsx
  src/components/edit-page/MemberListBox.tsx
  src/components/edit-page/NameAndColorChangeBox.tsx
  src/pages/edit.tsx
Labels: ✨ enhancement, 🖥️ui

#74 [페이지] 랜딩페이지 Gnb추가
  public/icon/whiteLogo.svg
  public/icon/whiteLogoName.svg
  src/common/header/Gnb.tsx
  src/components/landing/LandingHeader.tsx
  src/pages/index.tsx
Labels: 🖥️ui

#76 [API] axios instance 생성 및 interceptors 설정/ 요청 테스트
  src/api/cards.api.ts
  src/api/instance.ts
  src/api/test.api.ts
  src/components/common/Gnb.tsx
  src/constants/API.ts
  src/constants/MEDIAQUERIES.ts
  src/pages/index.tsx
  src/pages/sh.tsx
Labels: ✨ enhancement, ⚙️api

#82 [HotFix] API 요청 인터셉터 헤더 누락부분 긴급 수정
  src/api/instance.ts
  src/components/common/modal/card-confirm/CardConfirmModal.tsx
  src/components/common/modal/card-confirm/Comment.tsx
  src/components/common/modal/card-confirm/CommentForm.tsx
  src/components/common/modal/card-confirm/CommentList.tsx
  src/components/common/modal/card-confirm/ContentAndImageBox.tsx
  src/components/common/modal/card-confirm/MainBox.tsx
  src/components/common/modal/card-confirm/MockData.ts
  src/components/common/modal/card-confirm/ModalHeader.tsx
  src/components/common/modal/card-confirm/SideBox.tsx
  src/components/common/modal/card-confirm/TagBox.tsx
  src/components/common/modal/card-confirm/types.ts
Labels: ⚙️api, 🚨 hotfix!!

#84 [API] 대쉬보드 API 연결
  package-lock.json
  src/api/dashboards.api.ts
  src/components/common/SideBar.tsx
  src/components/common/modal/NewDashBoardModal.tsx
  yarn.lock
Labels: ⚙️api

#88 [API] users.api 등록
  src/api/users.api.ts
Labels: ⚙️api

#92 [HotFix] GitHub 파일 대소문자 오류 수정
  src/components/common/Modal/card-confirm/CommentItem.tsx
  src/components/common/modal/card-confirm/CommentItem.tsx
  src/styles/buttonStyle.ts
  src/styles/commonStyle.ts
  src/styles/datePickerStyle.ts
Labels: 🚨 hotfix!!

#94 [API] 마이페이지 api 연결
  src/api/users.api.ts
  src/components/common/SideBar.tsx
  src/components/my-page/ProfileChange.tsx
  src/pages/mypage.tsx
Labels: ⚙️api

#96 [API] auth.api 등록
  src/api/auth.api.ts
Labels: ⚙️api

#99 [API] 비밀번호 변경 api 작성
  src/api/users.api.ts
  src/components/common/SideBar.tsx
  src/components/common/modal/NewDashBoardModal.tsx
  src/components/my-page/PasswordChange.tsx
  src/components/my-page/ProfileChange.tsx
  yarn.lock
Labels: ⚙️api

#101 [페이지] 로그인/회원가입 페이지 API 연결
  src/components/common/form/Form.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: 🤓refactor, ⚙️api

#98 [API] 나의 대시보드 리액트쿼리 커스텀 훅 생성 및 적용
  src/api/dashboards.api.ts
  src/api/invitations.api.ts
  src/components/dashboard/my-board/DashBoardList.tsx
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/hooks/query/dashboards/useAcceptInvitationMutation.ts
  src/hooks/query/dashboards/useDashboardListQuery.ts
  src/hooks/query/dashboards/useMyInvitationListQuery.ts
  src/pages/my-dashboard.tsx
Labels: ⚙️api

#108 [API] 컬럼 API 추가
  src/api/cards.api.ts
  src/api/columns.api.ts
  src/components/common/modal/WarningModal.tsx
  src/components/dashboard/column/Column.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: ⚙️api

#110 [API] 마이페이지 프로필 변경
  src/api/users.api.ts
  src/components/common/ImgFileUpload.tsx
  src/components/common/SideBar.tsx
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/users/useMyPropfileQuery.ts
  src/hooks/query/users/useMyprofileEditMutation.ts
  src/hooks/query/users/useProfileImgUploadMutation.ts
Labels: ⚙️api

#114 [API] 상세 모달 API 구현
  src/api/comment.api.ts
  src/components/common/modal/card-detail/CardConfirmModal.tsx
  src/components/common/modal/card-detail/Comment.tsx
  src/components/common/modal/card-detail/CommentForm.tsx
  src/components/common/modal/card-detail/CommentItem.tsx
  src/components/common/modal/card-detail/CommentList.tsx
  src/components/common/modal/card-detail/ContentAndImageBox.tsx
  src/components/common/modal/card-detail/MOCK_DATA.ts
  src/components/common/modal/card-detail/MainBox.tsx
  src/components/common/modal/card-detail/ModalHeader.tsx
  src/components/common/modal/card-detail/SideBox.tsx
  src/components/common/modal/card-detail/TagBox.tsx
  src/hooks/query/cards/useDeleteCardMutation.ts
  src/hooks/query/cards/useDetailCardQuery.ts
  src/hooks/query/comments/useCommentsListQuery.ts
  src/hooks/query/comments/useCreateCommentsMutation.ts
  src/hooks/query/comments/useDeleteCommentsMutation.ts
  src/hooks/query/comments/useEditCommentsMutation.ts
  src/hooks/query/dashboards/useEditDashboardMutation.ts
  src/pages/dashboard/[id]/edit.tsx
  src/pages/hj.tsx
  src/types/CardDetail.ts
  src/utils/formatDate.ts
Labels: ⚙️api

#116 [API] 프로필 변경 API 연결 완료
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/users/useMyprofileEditMutation.ts
Labels: ⚙️api

#118 [API] 로그인/ 회원가입 페이지 리액트 쿼리 반영
  src/api/auth.api.ts
  src/components/template/SignLayout.tsx
  src/hooks/query/useSignInMutation.ts
  src/hooks/query/users/useSignUpMutation.ts
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: 🤓refactor, ⚙️api

#119 [API] 대시보드 페이지 컬럼, 카드 API 연결, API 문서 작성
  src/api/columns.api.ts
  src/components/common/Card.tsx
  src/components/dashboard/column/Column.tsx
  src/hooks/query/cards/useCardDetailQuery.ts
  src/hooks/query/cards/useCardListQuery.ts
  src/hooks/query/columns/useAddColumnMutation.ts
  src/hooks/query/columns/useColumnListQuery.ts
  src/pages/dashboard/[id]/index.tsx
Labels: ✨ enhancement, ⚙️api, 🖥️ui

#120 [나의 대시보드] 페이지네이션, 무한스크롤 구현
  src/api/invitations.api.ts
  src/components/dashboard/my-board/DashBoardList.tsx
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/components/dashboard/my-board/InvitedDashBoardListLoader.tsx
  src/hooks/query/dashboards/useDashboardListQuery.ts
  src/hooks/query/dashboards/useMyInvitationListQuery.ts
  src/hooks/useClickOutside.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useWindowSize.ts
Labels: ✨ enhancement

#122 [API] 비밀번호 변경 api 연결 성공
  src/components/common/ImgFileUpload.tsx
  src/components/landing/LandingHeader.tsx
  src/components/my-page/PasswordChange.tsx
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/auth/usePasswordChangeMutation.ts
  src/hooks/query/users/useMyPropfileQuery.ts
Labels: ⚙️api

#124 [UI] 셀렉트 박스 map으로 적용 및 스크롤 구현
  src/components/common/SelectBox.tsx
  src/components/common/SideBar.tsx
  src/pages/jy.tsx
Labels: 🐞bug, 🖥️ui

#126 [UI] 사이드바 페이지네이션 구현
  src/components/common/SideBar.tsx
  src/hooks/query/dashboards/useDashboardListQuery.ts
Labels: ✨ enhancement, 🖥️ui

#134 [공통] 폼 컴포넌트 수정
  public/icon/eyeOff.svg
  public/icon/eyeOn.svg
  src/components/common/form/Form.tsx
  src/constants/FORM_FIELDS.ts
Labels: ✨ enhancement, 🤓refactor, 🖥️ui

#137 [공통]DropDown 컴포넌트 구현
  src/components/common/DropDown.tsx
Labels: ✨ enhancement, 🖥️ui

#135 [UI/API] 대쉬보드 헤더 아바타 구현 및 내 이미지, 이름 렌더링
  package.json
  public/image/defaultImg.jpeg
  src/components/dashboard/AvatarList.tsx
  src/components/dashboard/DashBoardHeader.tsx
  src/components/dashboard/mockData.ts
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/users/useMyprofileEditMutation.ts
  yarn.lock
Labels: ✨ enhancement, ⚙️api, 🖥️ui

#131 [Fix] 셀렉트 박스
  src/components/common/SelectBox.tsx
  src/pages/jy.tsx
Labels: 🔨fix

#141 [API] 초대하기 모달 API 연결
  src/api/dashboards.api.ts
  src/components/common/modal/TeamMemberInviteModal.tsx
  src/constants/API.ts
  src/hooks/query/auth/useSignInMutation.ts
  src/hooks/query/dashboards/useTeamMemberInviteModalMutation.ts
  src/pages/dashboard/[id]/edit.tsx
Labels: ⚙️api

#147 [API] 헤더 api 구현 완료
  src/components/dashboard/DashBoardHeader.tsx
  src/hooks/query/member/useDashBoardMemberQuery.ts
  src/pages/my-dashboard.tsx
Labels: ⚙️api

#153 [리팩토링] 로그인 페이지 Import 경로 수정 & 초대하기 모달 수정 & mypage 폼 컴포넌트 연결오류 수정
  src/components/common/form/Form.tsx
  src/components/dashboard/DashBoardHeader.tsx
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/dashboards/useTeamMemberInviteModalMutation.ts
  src/pages/signin.tsx
  src/pages/signup.tsx
Labels: ✨ enhancement, 🤓refactor, 🔨fix

#155 [FIX] 셀렉트 박스 오류
  src/components/common/SelectBox.tsx
Labels: 🔨fix

#157 [API] 대시보드 수정, 삭제 API 구현
  src/components/common/Card.tsx
  src/components/common/modal/ColumnsManageModal.tsx
  src/components/dashboard/column/Column.tsx
  src/components/template/PageLayout.tsx
  src/hooks/query/columns/useDeleteColumnMutation.ts
  src/hooks/query/columns/useEditColumnMutation.ts
  src/pages/dashboard/[id]/index.tsx
Labels: ✨ enhancement, ⚙️api, 🖥️ui

#162 [FIX] 셀렉트박스 onChange 추가
  src/components/common/SelectBox.tsx
Labels: 🔨fix

#164 [FIX] 랜딩페이지 짤짤한 이슈 해결
  src/components/landing/Footer.tsx
Labels: 🔨fix

#168 [FIX] 사이드바 디자인 변경
  src/components/common/SideBar.tsx
Labels: 🔨fix

#170 [FIX] 프로필 이미지 아래 텍스트 추가
  src/components/my-page/ProfileChange.tsx
Labels: 🤓refactor, 🔨fix

#172 [FIX] 대시보드 헤더 초대하기 api 변경
  src/components/dashboard/DashBoardHeader.tsx
  src/hooks/query/dashboards/useInviteDashboardMutation.ts
  src/hooks/query/dashboards/useTeamMemberInviteModalMutation.ts
  src/pages/dashboard/[id]/edit.tsx
Labels: 🤓refactor, 🔨fix

#175 [FIX] 아바타 새로고침 해도 계속 나오게 수정
  src/api/members.api.ts
  src/components/dashboard/AvatarList.tsx
  src/components/dashboard/DashBoardHeader.tsx
  src/hooks/query/member/useDashBoardMemberQuery.ts
Labels: 🤓refactor, 🔨fix

#178 [FIX] 셀렉트 박스 export 코드 추가
  src/components/common/SelectBox.tsx
Labels: 🔨fix

#184 [리팩토링] 댓글 로직 수정
  src/components/common/modal/card-detail/Comment.tsx
  src/components/common/modal/card-detail/CommentForm.tsx
  src/components/common/modal/card-detail/CommentItem.tsx
  src/components/common/modal/card-detail/CommentList.tsx
  src/components/common/modal/card-detail/ModalHeader.tsx
  src/components/common/modal/card-detail/SideBox.tsx
  src/components/edit-page/InviteHistoryListBox.tsx
  src/components/edit-page/MemberListBox.tsx
  src/components/edit-page/NameAndColorChangeBox.tsx
  src/hooks/query/dashboards/useLoadInvitationQuery.ts
  src/pages/dashboard/[id]/edit.tsx
Labels: 🤓refactor

#183 [리팩토링] 비밀번호 validation 문구 수정
  src/components/common/form/Form.tsx
  src/constants/SCHEMA.ts
Labels: 🤓refactor

#180 [리팩토링] Dropdown 서식 수정 및 통일
  src/components/common/DropDown.tsx
  src/components/common/modal/card-detail/ModalHeader.tsx
Labels: 🤓refactor

#188 [FIX] 사이드바 찌그러지는 원형색상 해결
  src/components/common/CircleColor.tsx
  src/components/common/SideBar.tsx
  src/components/common/modal/NewDashBoardModal.tsx
  src/components/dashboard/AvatarList.tsx
Labels: 🐞bug, 🤓refactor, 🔨fix

#189 [페이지] 수정하기 클릭 시 할 일 수정 모달로 전환 구현
  src/components/common/Card.tsx
  src/components/common/modal/card-detail/CardConfirmModal.tsx
  src/components/common/modal/card-detail/ModalHeader.tsx
Labels: ⚙️api, 🖥️ui

#191 [refactor] 로그인 성공 시 토스트로 변경
  src/components/common/modal/card-detail/ModalHeader.tsx
  src/hooks/query/users/useSignUpMutation.ts
Labels: 🤓refactor

#185 [페이지] 대시보드 페이지 무한스크롤 및 레이아웃 구현
  src/api/cards.api.ts
  src/components/common/modal/NewDashBoardModal.tsx
  src/components/common/modal/ToDoCreateModal.tsx
  src/components/common/modal/ToDoEditModal.tsx
  src/components/dashboard/column/CardLoader.tsx
  src/components/dashboard/column/Column.tsx
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/cards/useCardImgUploadMutation.ts
  src/hooks/query/cards/useCardListQuery.ts
  src/hooks/query/members/useMemeberListQuery.ts
  src/hooks/useIntersectionObserver.ts
Labels: ✨ enhancement, ⚙️api, 🖥️ui

#193 [리팩토링] 로그인 페이지 배경 잘림 & 모달 헤더에 빠진 import 추가
  src/components/common/modal/card-detail/ModalHeader.tsx
  src/components/template/SignLayout.tsx
Labels: 🤓refactor

#196 [hotfix]
  src/hooks/query/columns/useColumnListQuery.ts
  src/hooks/query/dashboards/useLoadInvitationQuery.ts
  src/hooks/query/dashboards/useMembersListQuery.ts
  src/hooks/query/users/useMyPropfileQuery.ts
  src/hooks/query/users/useMyprofileEditMutation.ts
Labels: 🐞bug, 🚨 hotfix!!

#200 [fix] 라벨드 인풋 ref 에러 수정
  src/components/common/form/LabeledInput.tsx
Labels: 🔨fix

#198 [FIX] Circle 컴포넌트 스타일 수정 및 페이지네이션 초기화 안되게하기, active효과주기
  src/components/common/CircleColor.tsx
  src/components/common/SideBar.tsx
Labels: 🐞bug, 🔨fix, 🖥️ui

#205 [fix] 카드 바로 갱신안되는 이슈 해결
  src/components/common/modal/ToDoCreateModal.tsx
  src/components/dashboard/column/Column.tsx
  src/hooks/query/cards/useCreateCardMutation.ts
Labels: 🐞bug, 🔨fix, 🚨 hotfix!!

#210 [리팩토링] 드롭다운 박스 너비 수정
  src/components/common/DropDown.tsx
Labels: 🤓refactor

#207 [Fix] 대시보드 UI 오류 수정, 마이 대시보드에서 '새로운 대시보드' 로직 수정
  src/components/dashboard/column/Column.tsx
  src/components/dashboard/my-board/DashBoardList.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: 🔨fix, ⚙️api, 🖥️ui

#216 [ 리팩토링] 비밀번호 변경 수정
  src/hooks/query/auth/usePasswordChangeMutation.ts
Labels: 🤓refactor, 🔨fix

#211 [리팩토링] 로그아웃 구현 & 랜딩페이지 수정
  src/components/common/DropDown.tsx
  src/components/common/Gnb.tsx
  src/components/landing/LandingHeader.tsx
Labels: 🤓refactor

#218 [FIX] 셀렉트박스, 이미지업로드 컴포넌트 이슈 해결
  src/components/common/ImgFileUpload.tsx
  src/components/common/SelectBox.tsx
  src/components/common/modal/ToDoEditModal.tsx
  src/components/dashboard/mockData.ts
Labels: 🐞bug, 🤓refactor, 🔨fix

#223 [공통] 삭제 확인 모달 생성
  src/components/common/modal/ConfirmDeleteModal.tsx
  src/components/common/modal/card-detail/ModalHeader.tsx
  src/hooks/query/cards/useDeleteCardMutation.ts
Labels: ✨ enhancement, 🤓refactor, 🖥️ui

#220 [나의대시보드] 검색바 필터링 추가
  public/icon/closeIcon.svg
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/components/dashboard/my-board/SearchBar.tsx
  src/styles/theme.ts
Labels: ✨ enhancement

#226 [Fix] datePicker 마감일 선택 value 설정
  src/components/common/modal/ToDoCreateModal.tsx
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/pages/sh.tsx
Labels: 🐞bug, 🔨fix

#227 [할일 수정모달] 셀렉트박스 기존 데이터 적용
  src/components/common/modal/ToDoEditModal.tsx
Labels: 🐞bug, 🔨fix

#230 [FIX] 타입 지정
  src/api/cards.api.ts
  src/api/columns.api.ts
  src/api/comment.api.ts
  src/api/dashboards.api.ts
  src/api/invitations.api.ts
  src/components/common/Card.tsx
  src/components/common/ImgFileUpload.tsx
  src/components/common/modal/ColumnsManageModal.tsx
  src/components/common/modal/NewDashBoardModal.tsx
  src/components/common/modal/ToDoCreateModal.tsx
  src/components/common/modal/ToDoEditModal.tsx
  src/components/dashboard/DashBoardHeader.tsx
  src/components/dashboard/column/CardLoader.tsx
  src/components/dashboard/column/CardSkeleton.tsx
  src/components/dashboard/column/Column.tsx
  src/components/my-page/ProfileChange.tsx
  src/constants/API.ts
  src/hooks/query/cards/useCardDetailQuery.ts
  src/hooks/query/cards/useCardImgUploadMutation.ts
  src/hooks/query/cards/useCardListQuery.ts
  src/hooks/query/cards/useCreateCardMutation.ts
  src/hooks/query/cards/useDeleteCardMutation.ts
  src/hooks/query/cards/useEditCardMutation.ts
  src/hooks/query/columns/useAddColumnMutation.ts
  src/hooks/query/columns/useColumnListQuery.ts
  src/hooks/query/columns/useDeleteColumnMutation.ts
  src/hooks/query/columns/useEditColumnMutation.ts
  src/hooks/query/comments/useCommentsListQuery.ts
  src/hooks/query/comments/useCreateCommentsMutation.ts
  src/hooks/query/comments/useDeleteCommentsMutation.ts
  src/hooks/query/comments/useEditCommentsMutation.ts
  src/hooks/query/dashboards/useAcceptInvitationMutation.ts
  src/hooks/query/dashboards/useCancelInvitationMutation.ts
  src/hooks/query/dashboards/useCreateDashboardMutation.ts
  src/hooks/query/dashboards/useDashboardListQuery.ts
  src/hooks/query/dashboards/useDeleteDashboardMutation.ts
  src/hooks/query/dashboards/useDeleteMembersMutation.ts
  src/hooks/query/dashboards/useDetailDashboardQuery.ts
  src/hooks/query/dashboards/useEditDashboardMutation.ts
  src/hooks/query/dashboards/useLoadInvitationQuery.ts
  src/hooks/query/dashboards/useMembersListQuery.ts
  src/hooks/query/dashboards/useTeamMemberInviteModalMutation.ts
  src/hooks/query/members/useMemberListQuery.ts
  src/hooks/query/users/useMyProfileQuery.ts
  src/hooks/query/users/useMyprofileEditMutation.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/mj.tsx
  src/styles/CommonStyle.ts
  src/styles/theme.ts
Labels: 🤓refactor

#232 [Fix] auth.api 파일 & form 컴포넌트 타입에러 수정
  src/api/auth.api.ts
  src/components/common/form/Form.tsx
  src/components/my-page/PasswordChange.tsx
  src/components/my-page/ProfileChange.tsx
  src/constants/SCHEMA.ts
  src/hooks/query/auth/usePasswordChangeMutation.ts
  src/hooks/query/auth/useSignInMutation.ts
  src/hooks/query/users/useSignUpMutation.ts
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/types/Error.ts
  src/types/Form.ts
Labels: 🔨fix

#234 [FIX] 오타 수정
  src/components/common/SideBar.tsx
  src/components/my-page/ProfileChange.tsx
Labels: 🔨fix

#235 [나의 대시보드] 대시보드목록, 초대내역 스켈레톤 적용
  src/components/dashboard/my-board/DashBoardList.tsx
  src/components/dashboard/my-board/DashBoardSkeleton.tsx
  src/components/dashboard/my-board/InvitedDashBoardListLoader.tsx
  src/components/dashboard/my-board/InvitedDashBoardSkeleton.tsx
  src/hooks/query/dashboards/useDashboardListQuery.ts
  src/pages/sh.tsx
  src/styles/CommonStyle.ts
Labels: ✨ enhancement, 🖥️ui

#237 [Fix] 마이페이지 타입 에러 해결
  src/components/common/SelectBox.tsx
  src/components/common/SideBar.tsx
  src/components/common/form/Form.tsx
  src/components/my-page/PasswordChange.tsx
  src/components/my-page/ProfileChange.tsx
  src/hooks/query/auth/usePasswordChangeMutation.ts
  src/hooks/query/users/useMyprofileEditMutation.ts
Labels: 🔨fix

#246 [API] 대시보드 수정 페이지 이슈 해결
  src/components/common/modal/card-detail/CommentItem.tsx
  src/components/common/modal/card-detail/CommentList.tsx
  src/components/edit-page/InviteHistoryListBox.tsx
  src/components/edit-page/MemberListBox.tsx
  src/hooks/query/dashboards/useDeleteMembersMutation.ts
Labels: ⚙️api

#245 [Fix] 나의 대시보드, 할일 수정, 생성모달 NaN 이슈 및 버그 수정
  src/components/common/modal/ToDoCreateModal.tsx
  src/components/common/modal/ToDoEditModal.tsx
  src/components/dashboard/my-board/DashBoardList.tsx
  src/components/dashboard/my-board/DashBoardSkeleton.tsx
  src/components/dashboard/my-board/InvitedDashBoardList.tsx
  src/components/dashboard/my-board/InvitedDashBoardListLoader.tsx
  src/components/dashboard/my-board/NoInvitation.tsx
Labels: 🐞bug, 🔨fix

#247 [FIX] 스타일 수정
  src/components/common/Card.tsx
  src/components/common/button/AddIconButton.tsx
  src/components/dashboard/DashBoardHeader.tsx
  src/components/template/PageLayout.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/hj.tsx
  src/pages/js.tsx
  src/pages/jy.tsx
  src/pages/mj.tsx
  src/pages/mypage.tsx
  src/pages/sh.tsx
Labels: 🤓refactor, 🔨fix, 🖥️ui

#250 [API] 댓글 무한스크롤 및 초대 목록 렌더링 이슈 해결
  src/components/common/modal/card-detail/CommentList.tsx
  src/components/common/modal/card-detail/CommentListLoader.tsx
  src/hooks/query/dashboards/useLoadInvitationQuery.ts
  src/hooks/query/dashboards/useMembersListQuery.ts
Labels: ⚙️api
